name: py311
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - attrs=24.3.0
  - blas=1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.6.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2025.1.31
  - cfitsio=3.470
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cycler=0.11.0
  - debugpy=1.8.12
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fiona=1.10.1
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.10.6
  - geotiff=1.7.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=72.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kealib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libboost=1.71.0
  - libcurl=8.12.1
  - libdeflate=1.22
  - libffi=3.4.4
  - libgdal=3.6.2
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.20
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libzip=1.8.0
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - minizip=4.0.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - platformdirs=4.3.6
  - poppler=24.09.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.2.1
  - qhull=2020.2
  - requests=2.32.3
  - rtree=1.0.1
  - scikit-learn=1.6.1
  - setuptools=75.8.0
  - shapely=2.0.6
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.3.0
  - vc=14.42
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - affine==2.4.0
      - alabaster==1.0.0
      - babel==2.17.0
      - cffi==1.17.1
      - contextily==1.6.2
      - cryptography==44.0.1
      - deepdiff==8.2.0
      - docutils==0.21.2
      - et-xmlfile==2.0.0
      - execnet==2.1.1
      - fastjsonschema==2.21.1
      - geographiclib==2.0
      - geojson==3.2.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - igraph==0.11.8
      - imagesize==1.4.1
      - immutabledict==4.2.1
      - iniconfig==2.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lightsim2grid==0.8.2
      - llvmlite==0.44.0
      - matplotlib==3.8.4
      - matpowercaseframes==1.1.2
      - mercantile==1.2.1
      - narwhals==1.28.0
      - nbformat==5.10.4
      - numba==0.61.0
      - numpydoc==1.8.0
      - openpyxl==3.1.5
      - orderly-set==5.3.0
      - ortools==9.12.4544
      - pandapower==2.14.11
      - plotly==6.0.1
      - pluggy==1.5.0
      - power-grid-model==1.10.54
      - power-grid-model-io==1.2.115
      - protobuf==5.29.3
      - psycopg2==2.9.10
      - pycparser==2.22
      - pyogrio==0.10.0
      - pytest==8.3.4
      - pytest-xdist==3.6.1
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - rasterstats==0.20.0
      - referencing==0.36.2
      - rioxarray==0.19.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.24.0
      - scipy==1.13.1
      - simplejson==3.20.1
      - snowballstemmer==2.2.0
      - sphinx==8.2.1
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - structlog==25.1.0
      - tabulate==0.9.0
      - texttable==1.7.0
      - tqdm==4.67.1
      - xarray==2025.4.0
      - xlsxwriter==3.2.2
prefix: /scistor/ivm/mye500/miniconda3/envs/py311
